<?php

namespace webinarBundle\Repository;

/**
 * postsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postsRepository extends \Doctrine\ORM\EntityRepository
{
}
